title = "YarnSpinnerRbx"
gitRepoUrl = "https://github.com/ceast64/YarnSpinnerRbx"

gitSourceBranch = "main"
changelog = true
classOrder = []

apiCategories = [
  "callbacks",
  "handlers"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"

[home]
enabled = true
includeReadme = true

[[home.features]]
title = "Feature 1"
description = "This is a feature"
image = "https://url"

[[home.features]]
title = "Feature 2"
description = "This is a second feature"
image = "https://url"