title = "Silk"
gitRepoUrl = "https://github.com/ceast64/Silk"

gitSourceBranch = "main"
changelog = true
classOrder = []

apiCategories = [
  "callbacks",
  "handlers",
  "libraries",
  "constructor",
  "required"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "img/favicon.ico"
tagline = "Silk - a (WIP) Yarn Spinner runtime for Roblox."

[navbar.logo]
alt = "Silk Logo"
src = "img/silk-logo-dark.png"
srcDark = "img/silk-logo-light.png"

[footer]
style = "dark"
copyright = "Copyright © 2023 ceast64. Built with Moonwave and Docusaurus. Yarn ball icon from Flaticon."

[home]
enabled = true
includeReadme = true # disable once docs are finished

[[home.features]]
title = "Simple scripting."
description = "Write your dialogue in a lightweight language with minimal coding syntax that’s designed for writers."

[[home.features]]
title = "Expressive control."
description = "Define what your characters can do, and use commands to direct the scene."

[[home.features]]
title = "Incredible flexibility."
description = "You control what to do with the lines and commands that Yarn Spinner sends you."

[[classOrder]]
classes = ["Silk"]

[[classOrder]]
section = "Classes"
classes = ["CommandRegistry", "Dialogue", "Library", "Stack", "VirtualMachine"]

[[classOrder]]
section = "Datatypes"
classes = ["RawProgram", "YarnProgram"]

[[classOrder]]
section = "Libraries"
classes = ["Base64"]