namespace Silk;

internal static class Template
{
   public const string ScriptTemplate =
      """
      --!strict
      -- This file was automatically generated by Silk

      local HttpService = game:GetService("HttpService")

      local Silk = require(%SILKPATH%)

      local decoded = HttpService:JSONDecode(Silk.Base64.Decode("%YARNPROGRAM%"))

      local generate: () -> Silk.Program
      generate = function()
        local name, nodes, initial_values = Silk.DecodeProgram(decoded)

        return {
          name = name,
          nodes = nodes,
          initial_values = initial_values,

          strings = HttpService:JSONDecode(Silk.Base64.Decode("%YARNSTRINGS%")),
          clone = generate
        }
      end

      return generate()
      """;
}