--!strict
-- This file was automatically generated by YarnSpinnerRbx

local HttpService = game:GetService("HttpService")

local Yarn = require(%YARNPATH%)

local decoded = HttpService:JSONDecode(Yarn.base64.decode("%YARNPROGRAM%"))

local generate: () -> Yarn.Program
generate = function()
  local name, nodes, initial_values = Yarn.decodeProgram(decoded)

  return {
    name = name,
    nodes = nodes,
    initial_values = initial_values,

    strings = HttpService:JSONDecode(Yarn.base64.decode("%YARNSTRINGS%")),
    generate = generate
  }
end

return generate()
