--!strict
-- This file was automatically generated by YarnSpinnerRbx

local HttpService = game:GetService("HttpService")

local Yarn = require(%YARNPATH%)

local decoded = HttpService:JSONDecode(Yarn.base64.decode("%YARNPROGRAM%")) :: Yarn.RawProgram
local name, nodes, initial_values = Yarn.decodeProgram(decoded)

return {
    name = name,
    nodes = nodes,
    initial_values = initial_values,
    
    strings = HttpService:JSONDecode(Yarn.base64.decode("%YARNSTRINGS%"))
} :: Yarn.Program
